language: node_js
sudo: false

node_js:
  - "8"

addons:
  postgresql: "9.6"

services:
  - postgresql
  - redis-server

install:
  - pwd && npm install
  - env
  - psql -c "create database $BD_DATABASE_TEST;" -U $BD_USER

env:
  - CXX=g++-4.9